version: '3.7'

services:
    serve_dummy_model:
        build: ./serve_dummy_model
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./serve_dummy_model/:/usr/src/app/
        ports:
            - 8002:8000
        environment:
            - DATABASE_URL=postgresql://ppc_user:ppc_pass@service_db/ppc_uw_dev
    service_db:
        image: postgres:12.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ppc_user
            - POSTGRES_PASSWORD=ppc_pass
            - POSTGRES_DB=ppc_uw_dev
    model_monitoring:
        build: ./model_monitoring
        command: streamlit run main.py
        ports:
            - 80:8501
        environment:
            - DATABASE_URL=postgresql://ppc_user:ppc_pass@service_db/ppc_uw_dev
    nginx:
        image: nginx:latest
        ports:
            - 8080:8080
        volumes:
            - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - serve_dummy_model


volumes:
    postgres_data: